/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBtest;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.time.LocalDate;
import java.util.Date;

/**
 *
 * @author arvid
 */
public class AgentPage extends javax.swing.JFrame {

    private static InfDB idb;
    private ArrayList<AgentPage> agent;
    private static String anvandare;

    /**
     * Creates new form AgentPAge
     */
    public AgentPage(InfDB iidb, String anvandare) {
        initComponents();
        updateLabel(anvandare);
        this.anvandare = anvandare;
        idb = iidb;
        agent = new ArrayList<AgentPage>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label = new javax.swing.JLabel();
        andraLosenordField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        andraLosenordButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        utrustningField = new javax.swing.JTextField();
        utrustningButton = new javax.swing.JButton();
        alienButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label.setFont(new java.awt.Font("Sitka Banner", 3, 24)); // NOI18N
        label.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                labelInputMethodTextChanged(evt);
            }
        });

        andraLosenordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraLosenordFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Ändra lösenord:");

        andraLosenordButton.setText("OK");
        andraLosenordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andraLosenordButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Lägg till ny utrustning:");

        utrustningButton.setText("OK");
        utrustningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utrustningButtonActionPerformed(evt);
            }
        });

        alienButton.setText(">");
        alienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Lägg till en ny Alien:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(andraLosenordField)
                                    .addComponent(utrustningField))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(andraLosenordButton))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(utrustningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alienButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(andraLosenordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(andraLosenordButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(utrustningField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(utrustningButton))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alienButton)
                    .addComponent(jLabel4))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_labelInputMethodTextChanged
        // TODO add your handling code here:


    }//GEN-LAST:event_labelInputMethodTextChanged

    private void andraLosenordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraLosenordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_andraLosenordFieldActionPerformed

    private void andraLosenordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andraLosenordButtonActionPerformed
        // TODO add your handling code here:
        try {
            String losenordInput = andraLosenordField.getText();
            if (losenordInput.length() < 7) {

                String fraga = "UPDATE agent SET Losenord = '" + losenordInput + "' WHERE agent.Namn = '" + anvandare + "'";
                idb.update(fraga);
            } else {
                JOptionPane.showMessageDialog(null, "Ditt lösenord får inte överstiga 5 tecken!");
            }

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_andraLosenordButtonActionPerformed

    private void utrustningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utrustningButtonActionPerformed
        // TODO add your handling code here:
        try {
            LocalDate tid = LocalDate.now();
            System.out.println(tid);

            String utrustningInput = utrustningField.getText();
            String nyttUtrustningID = "SELECT MAX(Utrustnings_ID) + 1 FROM Utrustning";
            String utrustningId = idb.fetchSingle(nyttUtrustningID);
            //-------------------------------------------------------
            String utrustningFraga = "INSERT INTO utrustning (Utrustnings_ID, Benamning) VALUES ('" + utrustningId + "', '" + utrustningInput + "')";
            idb.insert(utrustningFraga);
            //-------------------------------------------------------
            String agentID = "SELECT Agent_id FROM agent where Namn = '" + anvandare + "'";
            String ettAgentID = idb.fetchSingle(agentID);
            //-------------------------------------------------------
            String utrustningID = "SELECT Utrustnings_id FROM utrustning where Benamning = '" + utrustningInput + "'";
            String ettUtrustningID = idb.fetchSingle(utrustningID);
            //-------------------------------------------------------
            String sambandFraga = "INSERT INTO innehar_utrustning (Agent_ID, Utrustnings_ID, Utkvitteringsdatum) VALUES ('" + ettAgentID + "','" + ettUtrustningID + "', '" + tid + "')";
            idb.insert(sambandFraga);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_utrustningButtonActionPerformed

    private void alienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienButtonActionPerformed
        // TODO add your handling code here:
        new RegistreraAlien(idb).setVisible(true);
    }//GEN-LAST:event_alienButtonActionPerformed
    private void updateLabel(String anvandare) {
        label.setText("Välkommen " + anvandare);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentPage(idb, anvandare).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alienButton;
    private javax.swing.JButton andraLosenordButton;
    private javax.swing.JTextField andraLosenordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label;
    private javax.swing.JButton utrustningButton;
    private javax.swing.JTextField utrustningField;
    // End of variables declaration//GEN-END:variables
}
