/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBtest;

import java.awt.HeadlessException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author arvid
 */
public class LaggTillAgent extends javax.swing.JFrame {

    private static InfDB idb;

    public LaggTillAgent(InfDB iidb) {
        initComponents();
        idb = iidb;
        fillCmb();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        losenField = new javax.swing.JTextField();
        namnField = new javax.swing.JTextField();
        telField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        omradeCmb = new javax.swing.JComboBox<>();
        adminCmb = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        losenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenFieldActionPerformed(evt);
            }
        });
        getContentPane().add(losenField);
        losenField.setBounds(201, 86, 157, 26);

        namnField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(namnField);
        namnField.setBounds(201, 130, 157, 26);
        getContentPane().add(telField);
        telField.setBounds(201, 174, 157, 26);

        jLabel1.setText("Lösenord:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 90, 62, 16);

        jLabel2.setText("Namn:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 130, 41, 16);

        jLabel3.setText("Telefonnr:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 180, 64, 16);

        jLabel4.setText("Område:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 220, 53, 16);

        jLabel5.setText("Admin:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 260, 45, 16);

        getContentPane().add(omradeCmb);
        omradeCmb.setBounds(201, 218, 157, 27);

        adminCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nej", "Ja" }));
        getContentPane().add(adminCmb);
        adminCmb.setBounds(200, 260, 157, 27);

        okButton.setText("Lägg till");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);
        okButton.setBounds(153, 308, 93, 29);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("Registrera ny Agent");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(86, 25, 249, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/dator/Desktop/rainbow-colors-153443_1280.png")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 440, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void losenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_losenFieldActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        try {

            //ta ut dagens datum i rätt form
            LocalDate dagensDatum = LocalDate.now();
            String losenord = losenField.getText();

            String tel = telField.getText();
            //använder regex för att validera att nummersträngen endast innehåller siffror

            String namn = namnField.getText();
            //kolla ifall alla fält är ifyllda
            //ta ut det som är valt i comboboxar
            String omradeNamn = omradeCmb.getSelectedItem().toString();
            String omradeFraga = "SELECT Omrades_ID from omrade where Benamning = '" + omradeNamn + "'";
            String omrade = idb.fetchSingle(omradeFraga);
            String adminStatus = adminCmb.getSelectedItem().toString();
            //ändra ja/nej till ja/nej för att det ska passa i databasen
            if (adminStatus.equals("Ja")) {
                adminStatus = "J";
            } else if (adminStatus.equals("Nej")) {
                adminStatus = "N";
            }
            Validation validering5 = new Validation(losenord);
            boolean rattLosenord = validering5.kollaLosen(losenord);
            
            Validation validering = new Validation(tel);
            boolean rattTel = validering.kollaInt(tel);

            Validation validering2 = new Validation(namn);
            boolean test2 = validering2.testaString(namn);

            Validation validering3 = new Validation(tel);
            boolean test3 = validering3.testaString(tel);

            Validation validering4 = new Validation(losenord);
            boolean test4 = validering4.testaString(losenord);
            //stämmer alla inputs kommer det läggas in i databasen
            if (rattLosenord == true && rattTel == true && test2 == true && test3 == true && test4 == true) {
                String regAgentFraga = "INSERT INTO agent (Agent_ID, Namn, Telefon, Anstallningsdatum, Administrator, Losenord, Omrade)\n"
                        + "SELECT MAX(Agent_ID) + 1, '" + namn + "', '" + tel + "', '" + dagensDatum + "','" + adminStatus + "','" + losenord + "','" + omrade + "' FROM agent";
                idb.insert(regAgentFraga);
                setVisible(false);
            }
            //skriv ut felmeddelanden + hjälp att rätta till fel
            /*if (corAgent == false) {
                JOptionPane.showMessageDialog(null, "Namnfältet måste börja med 'Agent'");

            }*/

        } catch (HeadlessException | InfException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_okButtonActionPerformed
    private void fillCmb() {
        try {
            String omradeFraga = "SELECT benamning FROM omrade";
            ArrayList<String> omradeLista = new ArrayList<String>();
            omradeLista = idb.fetchColumn(omradeFraga);
            for (String omrade : omradeLista) {
                omradeCmb.addItem(omrade);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaggTillAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaggTillAgent(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> adminCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField losenField;
    private javax.swing.JTextField namnField;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> omradeCmb;
    private javax.swing.JTextField telField;
    // End of variables declaration//GEN-END:variables
}
