/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBtest;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author arvid
 */
public class RegistreraAlien extends javax.swing.JFrame {

    /**
     * Creates new form registreraAlien
     */
    private static InfDB idb;
    private String platsensBenamning;
    //private String regex;

    public RegistreraAlien(InfDB iidb) {
        initComponents();
        idb = iidb;
        fillComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namnField = new javax.swing.JTextField();
        telField = new javax.swing.JTextField();
        ansvarigAgentField = new javax.swing.JTextField();
        skickaButton = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox<>();
        losenField = new javax.swing.JPasswordField();
        checkBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Lösenord:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 90, 62, 16);

        jLabel2.setText("Telefon:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 170, 51, 16);

        jLabel3.setText("Namn:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 130, 41, 16);

        jLabel4.setText("Plats:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(163, 267, 34, 16);

        jLabel5.setText("Ansvarig Agent:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 210, 100, 20);

        namnField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namnFieldActionPerformed(evt);
            }
        });
        getContentPane().add(namnField);
        namnField.setBounds(270, 120, 206, 26);

        telField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telFieldActionPerformed(evt);
            }
        });
        getContentPane().add(telField);
        telField.setBounds(270, 170, 206, 26);

        ansvarigAgentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansvarigAgentFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ansvarigAgentField);
        ansvarigAgentField.setBounds(270, 210, 206, 26);

        skickaButton.setText("OK");
        skickaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skickaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(skickaButton);
        skickaButton.setBounds(239, 317, 75, 29);

        getContentPane().add(comboBox);
        comboBox.setBounds(267, 263, 130, 27);

        losenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                losenFieldActionPerformed(evt);
            }
        });
        getContentPane().add(losenField);
        losenField.setBounds(270, 80, 206, 26);

        checkBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkBox.setText("Visa Lösenord");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });
        getContentPane().add(checkBox);
        checkBox.setBounds(480, 80, 140, 23);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setText("Registrera ny Alien");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 20, 270, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("/Users/dator/Desktop/Red_Color.jpeg")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 690, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namnFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namnFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namnFieldActionPerformed

    private void telFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telFieldActionPerformed

    private void ansvarigAgentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansvarigAgentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansvarigAgentFieldActionPerformed
    private void fillComboBox() {
        //fyll comboboxen med platser
        try {
            ArrayList<String> platsLista = new ArrayList<String>();
            String platserFraga = "SELECT Benamning FROM plats";
            platsLista = idb.fetchColumn(platserFraga);
            for (String platsen : platsLista) {
                comboBox.addItem(platsen);

            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    /*public boolean matches(String regex, String input) {
        //System.out.println(input.matches("[a-zA-Z]+"));
        input.matches("[a-zA-Z]+");
        return Pattern.matches(regex, input);
    }*/
    private void skickaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skickaButtonActionPerformed
        //knapp för att registrera en alien
        try {

            //skapar ett unikt ID för en alien
            String alienIDFraga = "SELECT MAX(Alien_ID) + 1 FROM Alien";
            String alienID_osynlig = idb.fetchSingle(alienIDFraga);

            //Tar ut dagens datum
            LocalDate tid_osynlig = LocalDate.now();

            String losenord_synlig = new String(losenField.getPassword());

            //----------------------------------------
            String namn_synlig = namnField.getText();
            //---------------------------------------
            String ansAgent = ansvarigAgentField.getText();
            String agentIDfraga = "SELECT agent_ID FROM agent WHERE namn = '" + ansAgent + "'";
            String agentID_synlig = idb.fetchSingle(agentIDfraga);
            //----------------------------------------
            String tel_synlig = telField.getText();
            //---------------------------------------------

            String platsensBenamning = comboBox.getSelectedItem().toString();
            String platsIDfraga = "SELECT plats_ID FROM plats WHERE Benamning = '" + platsensBenamning + "'";
            String platsen = idb.fetchSingle(platsIDfraga);
            //Validerar inputs från valideringsklassen
            Validation validering = new Validation(losenord_synlig);
            boolean test = validering.testaString(losenord_synlig);

            Validation validering2 = new Validation(namn_synlig);
            boolean test2 = validering2.testaString(namn_synlig);


            Validation validering3 = new Validation(ansAgent);
            boolean test3 = validering3.testaString(ansAgent);


            Validation validering4 = new Validation(tel_synlig);
            boolean test4 = validering4.testaString(tel_synlig);


            if (test == true && test2 == true && test3 == true && test4 == true) {
                String insertFraga = "INSERT INTO Alien (Alien_ID, Registreringsdatum, Losenord, Namn, Telefon, Plats, Ansvarig_Agent) VALUES ('" + alienID_osynlig + "', '" + tid_osynlig + "', '" + losenord_synlig + "', '" + namn_synlig + "', '" + tel_synlig + "', '" + platsen + "', '" + agentID_synlig + "' )";
                idb.insert(insertFraga);
            }
        } catch (InfException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_skickaButtonActionPerformed


    private void losenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_losenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_losenFieldActionPerformed

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
//Visar lösenordet om det önskas
        if (checkBox.isSelected()) {
            losenField.setEchoChar((char) 0);
        } else {
            losenField.setEchoChar('*');
        }
    }//GEN-LAST:event_checkBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistreraAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /*RegistreraAlien words = new RegistreraAlien(idb);
        words.matches("[A-Za-zåäö]+", "test");*/

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new RegistreraAlien(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansvarigAgentField;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField losenField;
    private javax.swing.JTextField namnField;
    private javax.swing.JButton skickaButton;
    private javax.swing.JTextField telField;
    // End of variables declaration//GEN-END:variables
}
