/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBtest;

import java.util.ArrayList;
import java.util.HashMap;
import oru.inf.InfDB;

/**
 *
 * @author arvid
 */
public class SeInformationAgent extends javax.swing.JFrame {

    private static InfDB idb;
    private String enData;

    private String valdAgent;

    /**
     * Creates new form SeInformationAgent
     */
    public SeInformationAgent(InfDB iidb) {
        initComponents();
        idb = iidb;
        fillAgentCmb();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agentCmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        agentIDLabel = new javax.swing.JLabel();
        telLabel = new javax.swing.JLabel();
        namnLabel = new javax.swing.JLabel();
        datumLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        omradeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        losenLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        agentCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentCmbActionPerformed(evt);
            }
        });
        getContentPane().add(agentCmb);
        agentCmb.setBounds(270, 40, 135, 27);

        jLabel1.setText("Agent ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 130, 59, 16);

        jLabel2.setText("Namn:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 160, 41, 16);

        jLabel3.setText("Telefon:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 190, 51, 16);

        jLabel4.setText("Anstallningsdatum:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 220, 123, 16);

        jLabel5.setText("Administrator:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 260, 91, 16);

        jLabel6.setText("Område:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(157, 332, 53, 16);

        agentIDLabel.setText("...");
        getContentPane().add(agentIDLabel);
        agentIDLabel.setBounds(280, 130, 158, 16);

        telLabel.setText("...");
        getContentPane().add(telLabel);
        telLabel.setBounds(280, 190, 158, 16);

        namnLabel.setText("...");
        getContentPane().add(namnLabel);
        namnLabel.setBounds(280, 160, 158, 16);

        datumLabel.setText("...");
        getContentPane().add(datumLabel);
        datumLabel.setBounds(280, 220, 158, 16);

        adminLabel.setText("...");
        getContentPane().add(adminLabel);
        adminLabel.setBounds(280, 260, 158, 16);

        omradeLabel.setText("...");
        getContentPane().add(omradeLabel);
        omradeLabel.setBounds(280, 332, 158, 16);

        jLabel7.setText("Lösenord:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(148, 298, 62, 16);

        losenLabel.setText("...");
        getContentPane().add(losenLabel);
        losenLabel.setBounds(280, 298, 158, 16);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setText("Visa info om Agent :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 40, 187, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon("/Users/dator/Desktop/rainbow-colors-153443_1280.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 540, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agentCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agentCmbActionPerformed
        // TODO add your handling code here:
        valdAgent = agentCmb.getSelectedItem().toString();
        fillLabels();
    }//GEN-LAST:event_agentCmbActionPerformed
    private void fillAgentCmb() {
        try {
            ArrayList<String> agenter = new ArrayList<String>();
            String alienFraga = "SELECT namn FROM agent";
            agenter = idb.fetchColumn(alienFraga);
            for (String agent : agenter) {
                agentCmb.addItem(agent);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }

    }

    private void fillLabels() {
        try {

            String fraga = "SELECT * FROM agent WHERE namn = '" + valdAgent + "'";
            HashMap<String, String> varden = new HashMap<String, String>();
            varden = idb.fetchRow(fraga);
            int i = 0;
            namnLabel.setText(valdAgent);
            for (String data : varden.values()) {
                enData = data;
                while (i <= varden.size()) {
                    if (i == 4) {
                        String omradeFraga = "Select Benamning FROM omrade WHERE Omrades_ID = '" + enData + "'";
                        String omradeBenamning = idb.fetchSingle(omradeFraga);
                        omradeLabel.setText(omradeBenamning);
                    }
                    if (i == 3) {
                        losenLabel.setText(enData);
                    }
                    if (i == 2) {
                        adminLabel.setText(enData);
                    }
                    if (i == 1) {
                        datumLabel.setText(enData);
                    }
                    if (i == 5) {
                        telLabel.setText(enData);
                    }
                    if (i == 6) {
                        agentIDLabel.setText(enData);
                    }

                    break;
                }
                i++;
            }

        } catch (Exception ex) {
            System.out.println(ex);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeInformationAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeInformationAgent(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabel;
    private javax.swing.JComboBox<String> agentCmb;
    private javax.swing.JLabel agentIDLabel;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel losenLabel;
    private javax.swing.JLabel namnLabel;
    private javax.swing.JLabel omradeLabel;
    private javax.swing.JLabel telLabel;
    // End of variables declaration//GEN-END:variables
}
