/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBtest;

<<<<<<< Updated upstream
import java.util.ArrayList;
import oru.inf.InfDB;

/**
 *
 * @author arvid
 */
public class TaBortAlien extends javax.swing.JFrame {

    private static InfDB idb;
    private static String alienInput;

    public TaBortAlien(InfDB iidb) {
        initComponents();
        idb = iidb;
        fillAlienCmb();
    }

    private void fillAlienCmb() {
        try {
            ArrayList<String> namnLista = new ArrayList<String>();
            String namnFraga = "SELECT Namn FROM Alien";
            namnLista = idb.fetchColumn(namnFraga);
            for (String namnet : namnLista) {
                alienCmb.addItem(namnet);

            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

=======
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
/**
 *
 * @author dator
 */
public class TaBortAlien extends javax.swing.JFrame {
private static InfDB idb;
private static String alienInput;
    /**
     * Creates new form TaBortAlien
     */
    public TaBortAlien (InfDB iidb) {
        initComponents();
        idb = iidb;
        fillAlienCmb();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
>>>>>>> Stashed changes
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< Updated upstream
        alienCmb = new javax.swing.JComboBox<>();
        taBortButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        getContentPane().add(alienCmb);
        alienCmb.setBounds(100, 87, 120, 40);

        taBortButton.setText("Ta bort");
        taBortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortButtonActionPerformed(evt);
            }
        });
        getContentPane().add(taBortButton);
        taBortButton.setBounds(250, 90, 89, 29);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Ta bort Alien");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 200, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/dator/Desktop/rainbow-colors-153443_1280.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 480, 210);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taBortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortButtonActionPerformed
        // TODO add your handling code here:
        try {
            alienInput = alienCmb.getSelectedItem().toString();
            String deleteAlien = "DELETE FROM Alien WHERE Namn = '" + alienInput + "'";
            idb.delete(deleteAlien);

        } catch (Exception ex) {
            System.out.println(ex);
        }  // TODO add your handling code here:
    
    }//GEN-LAST:event_taBortButtonActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
=======
        jLabel1 = new javax.swing.JLabel();
        alienCmb = new javax.swing.JComboBox<>();
        taBortKnapp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ta bort Alien :");

        alienCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alienCmbActionPerformed(evt);
            }
        });

        taBortKnapp.setText("Ta bort");
        taBortKnapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortKnappActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(alienCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(taBortKnapp)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(alienCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(taBortKnapp)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void fillAlienCmb() {
        try {
            ArrayList<String> namnLista = new ArrayList<String>();
            String namnFraga = "SELECT Namn FROM Alien";
            namnLista = idb.fetchColumn(namnFraga);
            for (String namnet : namnLista) {
                alienCmb.addItem(namnet);

            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    
    private void taBortKnappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortKnappActionPerformed
    
    try {
    alienInput = alienCmb.getSelectedItem().toString();
        String deleteAlien = "DELETE FROM Alien WHERE Namn = '" + alienInput + "'";
        idb.delete(deleteAlien);
        
    }
  
    catch (Exception ex) {
            System.out.println(ex);
    }  // TODO add your handling code here:
    }//GEN-LAST:event_taBortKnappActionPerformed

    private void alienCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alienCmbActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_alienCmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
>>>>>>> Stashed changes
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
<<<<<<< Updated upstream
            java.util.logging.Logger.getLogger(TaBortAlien

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortAlien

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortAlien

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortAlien

.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
=======
            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
>>>>>>> Stashed changes
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortAlien(idb).setVisible(true);
            }
        });
    }
<<<<<<< Updated upstream

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alienCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton taBortButton;
=======
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> alienCmb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton taBortKnapp;
>>>>>>> Stashed changes
    // End of variables declaration//GEN-END:variables
}
