/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DBtest;

<<<<<<< Updated upstream
import java.util.ArrayList;
import oru.inf.InfDB;

/**
 *
 * @author arvid
 */
public class TaBortUtrustning extends javax.swing.JFrame {

    private static InfDB idb;

    public TaBortUtrustning(InfDB iidb) {
        initComponents();
        idb = iidb;
        fillCmb();
    }

    private void fillCmb() {
        try {
            String utrustningFraga = "SELECT benamning FROM utrustning";
            ArrayList<String> utrustningLista = new ArrayList<String>();
            utrustningLista = idb.fetchColumn(utrustningFraga);
            for (String utrustning : utrustningLista) {
                utrustningCmb.addItem(utrustning);
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

=======
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
/**
 *
 * @author dator
 */
public class TaBortUtrustning extends javax.swing.JFrame {
private static InfDB idb;
private static String utrInput;
private static int utrObjekt;
    /**
     * Creates new form TaBortUtrustning
     */
    public TaBortUtrustning (InfDB iidb) {
        initComponents();
        idb = iidb;
        fillUtrCmb();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
>>>>>>> Stashed changes
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< Updated upstream
        utrustningCmb = new javax.swing.JComboBox<>();
        taBortButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        getContentPane().add(utrustningCmb);
        utrustningCmb.setBounds(104, 108, 117, 27);
=======
        taBortButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        utrCmb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
>>>>>>> Stashed changes

        taBortButton.setText("Ta bort");
        taBortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taBortButtonActionPerformed(evt);
            }
        });
<<<<<<< Updated upstream
        getContentPane().add(taBortButton);
        taBortButton.setBounds(281, 107, 89, 29);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Ta bort utrustning");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 30, 250, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/dator/Desktop/rainbow-colors-153443_1280.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 510, 230);
=======

        jLabel1.setText("Ta bort utrustning :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(utrCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(taBortButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(utrCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(taBortButton)
                .addGap(112, 112, 112))
        );
>>>>>>> Stashed changes

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taBortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taBortButtonActionPerformed
<<<<<<< Updated upstream
        // TODO add your handling code here:
        try{
        String utrustning = utrustningCmb.getSelectedItem().toString();
        String taBortFraga = "DELETE FROM utrustning where benamning = '"+utrustning+"';";
        idb.delete(taBortFraga);
        }
        catch(Exception ex){
            System.out.println(ex);
        }
        
=======
    try {
    utrInput = utrCmb.getSelectedItem().toString();
    utrObjekt = utrCmb.getSelectedItem();
    
        String deleteUtr = "DELETE FROM Utrustning WHERE Benamning = '" + utrInput + "'";
        String deleteUtrH = "DELETE FROM Innehar_Utrustning WHERE Utrustnings_ID = '" + utrObjekt + "'";
        
        idb.delete(deleteUtr);
        
    }
  
    catch (Exception ex) {
            System.out.println(ex);
    }        // TODO add your handling code here:
>>>>>>> Stashed changes
    }//GEN-LAST:event_taBortButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortUtrustning(idb).setVisible(true);
            }
        });
    }
<<<<<<< Updated upstream

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton taBortButton;
    private javax.swing.JComboBox<String> utrustningCmb;
=======
    
        private void fillUtrCmb() {
        try {
            ArrayList<String> utrLista = new ArrayList<String>();
            String utrFraga = "SELECT Benamning FROM Utrustning";
            utrLista = idb.fetchColumn(utrFraga);
            for (String utr : utrLista) {
                utrCmb.addItem(utr);

            }
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton taBortButton;
    private javax.swing.JComboBox<String> utrCmb;
>>>>>>> Stashed changes
    // End of variables declaration//GEN-END:variables
}
